### ISSUE TITLE
Can you show me how the quantile is designed in this model?

### ISSUE THREAD

**Issue by qinhaohcen** [zillow/quantile-forest#2]
Can you show me how the quantile is designed in this model?

**Comment by reidjohnson** [comment]
Hi @qinhaohcen, the actual quantile functions are written in Cython and are defined [here](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_quantile_forest_fast.pyx#L124-L237) (unweighted quantile) and [here](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_quantile_forest_fast.pyx#L240-L424) (weighted quantile). The functions are then called for each sample on its list of shared leaf members.

**Comment by qinhaohcen** [comment]
> Hi @qinhaohcen, the actual quantile functions are written in Cython and are defined [here](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_quantile_forest_fast.pyx#L124-L237) (unweighted quantile) and [here](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_quantile_forest_fast.pyx#L240-L424) (weighted quantile). The functions are then called for each sample on its list of shared leaf members.

Yes, I noticed this pyd file named  “_quantile_forest_fast.cp39-win_amd64”.  Thanks for your sharing generously！

**Comment by qinhaohcen** [comment]
> Hi @qinhaohcen, the actual quantile functions are written in Cython and are defined [here](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_quantile_forest_fast.pyx#L124-L237) (unweighted quantile) and [here](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_quantile_forest_fast.pyx#L240-L424) (weighted quantile). The functions are then called for each sample on its list of shared leaf members.

Is the   x=q*(N+1-2C)+C   equal to  x=q*（N+1-C)+(1-q)*C  ? How this formula was derived？

**Comment by reidjohnson** [comment]
That formula's based on the derivation provided in Wikipedia [here](https://en.wikipedia.org/wiki/Percentile#The_linear_interpolation_between_closest_ranks_method).

**Comment by qinhaohcen** [comment]
> That formula's based on the derivation provided in Wikipedia [here](https://en.wikipedia.org/wiki/Percentile#The_linear_interpolation_between_closest_ranks_method).

May I get a screenshot or word file including the  content from you by email？ I can't connect to Wikipedia. This is my email address：690838038@qq.com.

**Comment by reidjohnson** [comment]
@qinhaohcen: Sure, here's a PDF of that content: [Percentile - Wikipedia.pdf](https://github.com/zillow/quantile-forest/files/9793779/Percentile.-.Wikipedia.pdf).

**Comment by qinhaohcen** [comment]
> @qinhaohcen: Sure, here's a PDF of that content: [Percentile - Wikipedia.pdf](https://github.com/zillow/quantile-forest/files/9793779/Percentile.-.Wikipedia.pdf).

Thank you very much!
