### ISSUE TITLE
RandomForestQuantileRegression Multi-output

### ISSUE THREAD

**Issue by rafael-fontana-crespo** [zillow/quantile-forest#23]
Hello author, 

First of all, thanks and congratulations for your magnificent work. I was trying to compute prediction intervals with RandomForestQuantileRegression using a multi-output approach (t+1 -> t+n)... I checked and in the code seems to be something as #ToDo...  I was wondering if you are planning for an implementation soon, since will be really useful.

Look forward to your answer,
Thank you
Rafael

**Comment by reidjohnson** [comment]
Thanks for your interest in the package and for opening this issue!

You're correct that the multi-output approach is marked as a to-do, though currently unplanned. I understand that it could be quite useful, so I'll scope out the issue to see how much work a multi-output implementation would be.

In the meantime, as you may or may not be aware, scikit-learn offers a [MultiOutputRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html) that should be able to wrap the RandomForestQuantileRegressor estimator, which can serve as a stopgap solution despite some downsides.

**Comment by rafael-fontana-crespo** [comment]
Thank you very much for your answer, and for your suggestion

**Comment by reidjohnson** [comment]
@rafael-fontana-crespo: Based on initial scoping, implementing multi-target outputs should be feasible. I've created a pull request with an initial implementation, though it will take a little more time to update the unit tests and documentation.

In the meantime, if you have a suggested dataset for testing multi-target outputs, please let me know.

**Comment by reidjohnson** [comment]
@rafael-fontana-crespo: Multiple outputs are now supported in v1.3.0. Details on usage are in the user guide ([here](https://zillow.github.io/quantile-forest/user_guide.html#making-predictions)) and the new multiple-output quantile regression example ([here](https://zillow.github.io/quantile-forest/auto_examples/plot_quantile_multioutput.html#sphx-glr-auto-examples-plot-quantile-multioutput-py)). Please feel free to follow up with any further issues.

**Comment by rafael-fontana-crespo** [comment]
Thank you very much for you work
