### ISSUE TITLE
quantile-forest not installable via poetry install on M1/M2 chip Macbooks

### ISSUE THREAD

**Issue by brdeleeuw** [zillow/quantile-forest#4]
Having `quantile-forest` as dependency in a `pyproject.toml` and then installing via `poetry install` does not seem to work:

```
  SolverProblemError

  Because <project name> depends on quantile-forest (1.0.2) which doesn't match any versions, version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

This only seems to happen on the ARM-based Macbooks (M1/M2) and not on the older intel-based versions. Installing from source does work on the ARM-based systems.

Presumably the right wheels for those versions are not available on PyPi: https://pypi.org/project/quantile-forest/#files 

Would it be possible to add the appropriate wheels for those versions, or maybe a source distribution that will install on the M1/M2 chips? I'd love to hear if there are other solutions as well. 

Thanks!

**Comment by reidjohnson** [comment]
Thanks for raising this issue! I've updated the build process to include wheels for ARM64-based Macs in the most recent release. Feel free to follow-up if you run into any issues using them.

**Comment by robertritz** [comment]
Wow, I should have just asked! I ended up using a Docker container to get it working on my M1. Thanks Reid!

**Comment by brdeleeuw** [comment]
Great, thanks a lot for solving this so quickly!
