### ISSUE TITLE
Missing Parameters in interpolation for the function predict

### ISSUE THREAD

**Issue by felix7602** [zillow/quantile-forest#60]
Hi reidjohnson,

I found that the documentation regarding the interpolation parameter of the predict method is incomplete in describing the options.

Here is the complete list of options for the interpolation parameter:
Use one of: dict_keys(['inverted_cdf', 'averaged_inverted_cdf', 'closest_observation', 'interpolated_inverted_cdf', 'hazen', 'weibull', 'linear', 'median_unbiased', 'normal_unbiased', 'lower', 'higher', 'midpoint', 'nearest'])

But in the documentation:
interpolation : {"linear", "lower", "higher", "midpoint", "nearest"},                 default="linear"
    Specifies the interpolation method to use when the desired
    quantile lies between two data points ``i < j``:

    - If "linear", then ``i + (j - i) * fraction``, where ``fraction``
      is the fractional part of the index surrounded by ``i`` and
      ``j``.
    - If "lower", then ``i``.
    - If "higher", then ``j``.
    - If "nearest", then ``i`` or ``j``, whichever is nearest.
    - If "midpoint", then ``(i + j) / 2``.

**Comment by reidjohnson** [comment]
@felix7602, thanks for noting the issue.

You're correct that these additional options may be available with the default parameter settings, where `max_samples_leaf = 1`. In these cases, we apply optimizations that allow us to leverage the NumPy implementation for calculating quantiles ([np.quantile](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html)), which accept additional interpolation methods. However, for other values of `max_samples_leaf`, we use an implementation for calculating quantiles that only allows the interpolation methods specified in the documentation.

So a challenge here is that the additional interpolation options are only available with particular model parameterizations, and in those cases the additional options depend on the specific version of NumPy (and are thus subject to change). Perhaps one way of documenting the availability of these additional options is to provide a note that when `max_samples_leaf = 1`, the specific options will depend on those available in Numpy.

That said, your thoughts on the appropriate way of documenting these additional interpolation options are welcome.

**Comment by reidjohnson** [comment]
@felix7602, thanks for closing the issue. I'll keep it as an open item to update the documentation to reflect these options.
