### ISSUE TITLE
Regarding the Calculation of Quantiles in the Model

### ISSUE THREAD

**Issue by felix7602** [zillow/quantile-forest#61]
I found that the quantiles obtained through the process in the screenshot differ from those predicted directly by the model. 

When I aggregate all samples from the corresponding nodes of all trees into one array, sort them, and then find the quantile, I notice that the result starts to differ from the model's direct prediction beyond the fourth or fifth decimal place.

This discrepancy occurs despite trying different settings:

1. max_samples_leaf = 1 (default): In this case, each tree's leaf node for a new sample X contains only one sample.
2. max_samples_leaf = None: Here, each tree's leaf node for a new sample X contains many samples. (this is the process in the screenshot)

The difference in precision between my manual calculation and the model's prediction suggests that there might be additional internal factors or optimizations in the model's quantile estimation process that are not fully replicated in my manual method. Could you tell me what the problem is?

If we need all the sample data in the leaf nodes to manually calculate the quantiles, can we still achieve this step if the model is initialized with the default setting of max_samples_leaf = 1?

I really appreciate your work and I'm looking forward to your reply.
![qf](https://github.com/zillow/quantile-forest/assets/157549069/677938aa-62f7-4463-8590-02880bedfac2)

Felix

**Comment by felix7602** [comment]
I already know where the problem was. This index list **y_train_leaves** starts from 1 instead of 0 (because zero is used for padding to align the length of each leaf node). When using it, subtract one.

**Comment by reidjohnson** [comment]
Thanks for following up, you're exactly right -- 0 is used for padding, so the leave indices should start from 1.
