### ISSUE TITLE
version.txt missing in PyPI's source distribution

### ISSUE THREAD

**Issue by HuashiSCNU0303** [zillow/quantile-forest#7]
Hello, first of all, thanks for this fast and good implementation of quantile random forest!
I'm using this package in CentOS on arm64, and there is no built distribution in PyPI. When I execute 'pip install quantile-forest', the building process throws the error like this:

(spark) E:\quantile-forest-1.1.2>python setup.py install
Partial import of quantile-forest during the build process.
Traceback (most recent call last):
  File "E:\quantile-forest-1.1.2\setup.py", line 28, in <module>
    __version__ = write_version_py()
  File "E:\quantile-forest-1.1.2\setup.py", line 19, in write_version_py
    with open(os.path.join("quantile_forest", "version.txt")) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'quantile_forest\\version.txt'

I think that's because the file 'version.txt' in the 'quantile-forest' folder changes to 'version.py' in PyPI's source distribution. I'll appreciated if you can fix the problem, since I need to directly install this library via PyPI. Thank you in advance!

**Comment by reidjohnson** [comment]
Thanks for reporting this issue! It should now be fixed with the most recent release. Please let me know otherwise.

**Comment by HuashiSCNU0303** [comment]
Thanks for your help. Now I can install the package via PyPI.
