### ISSUE TITLE
Unable to instantiate without positional arguments

### ISSUE THREAD

**Issue by brentonmallen1** [zillow/quantile-forest#8]
I'm attempting to use skops to save and load the model, but running into an issue (https://github.com/skops-dev/skops/issues/383) there with loading due to the requirement of two positional arguments when the model is instantiated using the `__new__` method.  Calling the method on the object leads to the `__cinit__` method (https://github.com/zillow/quantile-forest/blob/efc1ebd08f1431a33532a418896cc14f22e22be3/quantile_forest/_quantile_forest_fast.pyx#L568) which requires two positional arguments.

Would it be possible to make these optional or have some default value for instantiation?

**Comment by reidjohnson** [comment]
Thanks for reporting the issue! Will work on a resolution.

**Comment by reidjohnson** [comment]
It appears that this issue falls under the scope of the skops project. As I understand you've also reported the issue there, I've created a fork of skops with the relevant changes needed to support saving and loading quantile-forest models and referenced your issue in the PR. It's not clear to me that supporting this package will be within the scope of skops, but we can continue to track the issue there.

**Comment by reidjohnson** [comment]
It's also worth mentioning that I did try using default values for all arguments to the `__cinit__` method, along with other small changes, but I haven't been able to find a fix in this package that fully rectifies the issue (i.e., even if the model loads without raising the above error, it's loaded incorrectly without updates to the skops package itself).

**Comment by reidjohnson** [comment]
It's also worth mentioning that I did try using default values for all arguments to the `__cinit__` method (thanks for the suggestion!), along with other small changes, but I haven't been able to find a fix in this package that fully rectifies the issue (i.e., even if the model loads without raising the above error, it's loaded incorrectly without updates directly to skops).

**Comment by brentonmallen1** [comment]
hmm okay, I appreciate you for taking a look at this. I wasn't sure which side would be a more appropriate place to handle this, but I'll mark this one closed and pursue it on their end.  Thanks again and take care!
